// 酸碱中和反应
import { REACTION_TYPES } from "../../constants/labConfig";

export const acidBaseRecipes = {
  "HCl+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + NaOH → NaCl + H₂O",
    color: "#f472b6",
    ph: 7,
    tempDelta: 15,
    effect: "heat",
    description: "强酸强碱中和，放热明显，溶液呈中性",
  },
  "H2SO4+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O",
    color: "#fb7185",
    ph: 7,
    tempDelta: 18,
    effect: "heat",
    description: "硫酸与氢氧化钠中和，生成硫酸钠和水",
  },
  "H2SO4+Ca(OH)2": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + Ca(OH)₂ → CaSO₄↓ + 2H₂O",
    color: "#c4b5fd",
    ph: 7,
    tempDelta: 12,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成微溶的硫酸钙沉淀",
  },
  "HCl+KOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + KOH → KCl + H₂O",
    color: "#e879f9",
    ph: 7,
    tempDelta: 14,
    effect: "heat",
    description: "盐酸与氢氧化钾中和反应",
  },
  "HNO3+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HNO₃ + NaOH → NaNO₃ + H₂O",
    color: "#f9a8d4",
    ph: 7,
    tempDelta: 13,
    effect: "heat",
    description: "硝酸与氢氧化钠中和反应",
  },
  "CH3COOH+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "CH₃COOH + NaOH → CH₃COONa + H₂O",
    color: "#fbbf24",
    ph: 8,
    tempDelta: 8,
    effect: "heat",
    description: "弱酸强碱中和，放热较少，溶液呈碱性",
  },
  "HCl+NH3H2O": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + NH₃·H₂O → NH₄Cl + H₂O",
    color: "#67e8f9",
    ph: 6,
    tempDelta: 10,
    effect: "heat",
    description: "强酸弱碱中和，溶液呈弱酸性",
  },
  "H2SO4+Ba(OH)2": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + Ba(OH)₂ → BaSO₄↓ + 2H₂O",
    color: "#dbeafe",
    ph: 7,
    tempDelta: 16,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "生成白色硫酸钡沉淀",
  },
};
