// 产气反应
import { REACTION_TYPES } from "../../constants/labConfig";

export const gasProductionRecipes = {
  "HCl+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + Na₂CO₃ → 2NaCl + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 4,
    tempDelta: -3,
    effect: "gas",
    description: "盐酸与碳酸钠反应，产生二氧化碳气体",
  },
  "HCl+NaHCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "HCl + NaHCO₃ → NaCl + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 5,
    tempDelta: -5,
    effect: "gas",
    description: "盐酸与碳酸氢钠反应，产生二氧化碳",
  },
  "H2SO4+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "H₂SO₄ + Na₂CO₃ → Na₂SO₄ + H₂O + CO₂↑",
    color: "#67e8f9",
    ph: 3,
    tempDelta: 2,
    effect: "gas",
    description: "硫酸与碳酸钠反应，产生二氧化碳",
  },
  "HCl+CaCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂↑",
    color: "#7dd3fc",
    ph: 4,
    tempDelta: 5,
    effect: "gas",
    description: "盐酸与碳酸钙反应，固体溶解并产生气泡",
  },
  "HCl+BaCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + BaCO₃ → BaCl₂ + H₂O + CO₂↑",
    color: "#93c5fd",
    ph: 4,
    tempDelta: 3,
    effect: "gas",
    description: "盐酸与碳酸钡反应，产生二氧化碳",
  },
  "HNO3+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HNO₃ + Na₂CO₃ → 2NaNO₃ + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 4,
    tempDelta: -2,
    effect: "gas",
    description: "硝酸与碳酸钠反应",
  },
  "H2SO4+NaHCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "H₂SO₄ + 2NaHCO₃ → Na₂SO₄ + 2H₂O + 2CO₂↑",
    color: "#7dd3fc",
    ph: 4,
    tempDelta: -4,
    effect: "gas",
    description: "硫酸与碳酸氢钠反应",
  },
  "NH4Cl+NaOH": {
    type: REACTION_TYPES["Gas Production"],
    equation: "NH₄Cl + NaOH →(加热) NaCl + H₂O + NH₃↑",
    color: "#67e8f9",
    ph: 12,
    tempDelta: 15,
    effect: "gas",
    description: "铵盐与碱加热产生氨气（检验铵根离子）",
  },
  "(NH4)2SO4+NaOH": {
    type: REACTION_TYPES["Gas Production"],
    equation: "(NH₄)₂SO₄ + 2NaOH →(加热) Na₂SO₄ + 2H₂O + 2NH₃↑",
    color: "#67e8f9",
    ph: 12,
    tempDelta: 18,
    effect: "gas",
    description: "硫酸铵与碱加热产生氨气",
  },
};
