// 反应配方统一导出
// 按反应类型拆分，便于维护

import { REACTION_TYPES } from "../../constants/labConfig";

// 试剂定义
export { reagents, getReagentImage } from "./reagents";

// 补充反应
import {
  indicatorRecipes,
  metalWaterRecipes,
  amphotericRecipes,
  ionTestRecipes,
  nonmetalOxideRecipes,
  ironCopperRecipes,
  industrialRecipes,
  organicRecipes,
  moreRedoxRecipes,
  morePrecipitateRecipes,
} from "./supplementRecipes";

// ==================== 酸碱中和反应 ====================
const acidBaseRecipes = {
  "HCl+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + NaOH → NaCl + H₂O",
    color: "#f472b6",
    ph: 7,
    tempDelta: 15,
    effect: "heat",
    description: "强酸强碱中和，放热明显，溶液呈中性",
  },
  "H2SO4+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O",
    color: "#fb7185",
    ph: 7,
    tempDelta: 18,
    effect: "heat",
    description: "硫酸与氢氧化钠中和",
  },
  "HCl+KOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + KOH → KCl + H₂O",
    color: "#e879f9",
    ph: 7,
    tempDelta: 14,
    effect: "heat",
    description: "盐酸与氢氧化钾中和",
  },
  "HNO3+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "HNO₃ + NaOH → NaNO₃ + H₂O",
    color: "#f9a8d4",
    ph: 7,
    tempDelta: 13,
    effect: "heat",
    description: "硝酸与氢氧化钠中和",
  },
  "CH3COOH+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "CH₃COOH + NaOH → CH₃COONa + H₂O",
    color: "#fbbf24",
    ph: 8,
    tempDelta: 8,
    effect: "heat",
    description: "弱酸强碱中和，溶液呈碱性",
  },
  "HCl+NH3H2O": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + NH₃·H₂O → NH₄Cl + H₂O",
    color: "#67e8f9",
    ph: 6,
    tempDelta: 10,
    effect: "heat",
    description: "强酸弱碱中和",
  },
  "H2SO4+Ba(OH)2": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + Ba(OH)₂ → BaSO₄↓ + 2H₂O",
    color: "#dbeafe",
    ph: 7,
    tempDelta: 16,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "生成白色硫酸钡沉淀",
  },
  "H2SO4+Ca(OH)2": {
    type: REACTION_TYPES.Neutralization,
    equation: "H₂SO₄ + Ca(OH)₂ → CaSO₄↓ + 2H₂O",
    color: "#c4b5fd",
    ph: 7,
    tempDelta: 12,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成微溶的硫酸钙沉淀",
  },
};

// ==================== 产气反应 ====================
const gasProductionRecipes = {
  "HCl+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + Na₂CO₃ → 2NaCl + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 4,
    tempDelta: -3,
    effect: "gas",
    description: "盐酸与碳酸钠反应，产生二氧化碳",
  },
  "HCl+NaHCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "HCl + NaHCO₃ → NaCl + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 5,
    tempDelta: -5,
    effect: "gas",
    description: "盐酸与碳酸氢钠反应",
  },
  "HCl+CaCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂↑",
    color: "#7dd3fc",
    ph: 4,
    tempDelta: 5,
    effect: "gas",
    description: "盐酸与碳酸钙反应",
  },
  "HCl+BaCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HCl + BaCO₃ → BaCl₂ + H₂O + CO₂↑",
    color: "#93c5fd",
    ph: 4,
    tempDelta: 3,
    effect: "gas",
    description: "盐酸与碳酸钡反应",
  },
  "H2SO4+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "H₂SO₄ + Na₂CO₃ → Na₂SO₄ + H₂O + CO₂↑",
    color: "#67e8f9",
    ph: 3,
    tempDelta: 2,
    effect: "gas",
    description: "硫酸与碳酸钠反应",
  },
  "H2SO4+NaHCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "H₂SO₄ + 2NaHCO₃ → Na₂SO₄ + 2H₂O + 2CO₂↑",
    color: "#7dd3fc",
    ph: 4,
    tempDelta: -4,
    effect: "gas",
    description: "硫酸与碳酸氢钠反应",
  },
  "HNO3+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2HNO₃ + Na₂CO₃ → 2NaNO₃ + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 4,
    tempDelta: -2,
    effect: "gas",
    description: "硝酸与碳酸钠反应",
  },
  "HNO3+NaHCO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "HNO₃ + NaHCO₃ → NaNO₃ + H₂O + CO₂↑",
    color: "#a5f3fc",
    ph: 5,
    tempDelta: -3,
    effect: "gas",
    description: "硝酸与碳酸氢钠反应",
  },
  "CH3COOH+Na2CO3": {
    type: REACTION_TYPES["Gas Production"],
    equation: "2CH₃COOH + Na₂CO₃ → 2CH₃COONa + H₂O + CO₂↑",
    color: "#fbbf24",
    ph: 6,
    tempDelta: -2,
    effect: "gas",
    description: "醋酸与碳酸钠反应（弱酸也能与碳酸盐反应）",
  },
  "NH4Cl+NaOH": {
    type: REACTION_TYPES["Gas Production"],
    equation: "NH₄Cl + NaOH →(加热) NaCl + H₂O + NH₃↑",
    color: "#67e8f9",
    ph: 12,
    tempDelta: 15,
    effect: "gas",
    description: "铵盐与碱加热产生氨气（检验铵根离子）",
  },
  "(NH4)2SO4+NaOH": {
    type: REACTION_TYPES["Gas Production"],
    equation: "(NH₄)₂SO₄ + 2NaOH →(加热) Na₂SO₄ + 2H₂O + 2NH₃↑",
    color: "#67e8f9",
    ph: 12,
    tempDelta: 18,
    effect: "gas",
    description: "硫酸铵与碱加热产生氨气",
  },
  "NH4NO3+NaOH": {
    type: REACTION_TYPES["Gas Production"],
    equation: "NH₄NO₃ + NaOH →(加热) NaNO₃ + H₂O + NH₃↑",
    color: "#67e8f9",
    ph: 12,
    tempDelta: 16,
    effect: "gas",
    description: "硝酸铵与碱加热产生氨气",
  },
};

// ==================== 沉淀反应 ====================
const precipitationRecipes = {
  "AgNO3+NaCl": {
    type: REACTION_TYPES.Precipitation,
    equation: "AgNO₃ + NaCl → AgCl↓ + NaNO₃",
    color: "#e5e7eb",
    ph: 5,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "生成白色氯化银沉淀（检验氯离子）",
  },
  "AgNO3+HCl": {
    type: REACTION_TYPES.Precipitation,
    equation: "AgNO₃ + HCl → AgCl↓ + HNO₃",
    color: "#e5e7eb",
    ph: 1,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "检验氯离子：生成白色沉淀",
  },
  "AgNO3+KCl": {
    type: REACTION_TYPES.Precipitation,
    equation: "AgNO₃ + KCl → AgCl↓ + KNO₃",
    color: "#e5e7eb",
    ph: 5,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "硝酸银与氯化钾反应",
  },
  "BaCl2+Na2SO4": {
    type: REACTION_TYPES.Precipitation,
    equation: "BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl",
    color: "#f1f5f9",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "生成白色硫酸钡沉淀（检验硫酸根离子）",
  },
  "BaCl2+H2SO4": {
    type: REACTION_TYPES.Precipitation,
    equation: "BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl",
    color: "#f1f5f9",
    ph: 1,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "检验硫酸根离子：生成白色沉淀",
  },
  "Ba(NO3)2+Na2SO4": {
    type: REACTION_TYPES.Precipitation,
    equation: "Ba(NO₃)₂ + Na₂SO₄ → BaSO₄↓ + 2NaNO₃",
    color: "#f1f5f9",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "硝酸钡与硫酸钠反应",
  },
  "CaCl2+Na2CO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "CaCl₂ + Na₂CO₃ → CaCO₃↓ + 2NaCl",
    color: "#fefce8",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成白色碳酸钙沉淀",
  },
  "Ca(OH)2+Na2CO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "Ca(OH)₂ + Na₂CO₃ → CaCO₃↓ + 2NaOH",
    color: "#fefce8",
    ph: 12,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "氢氧化钙与碳酸钠反应（工业制烧碱）",
  },
  "BaCl2+Na2CO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "BaCl₂ + Na₂CO₃ → BaCO₃↓ + 2NaCl",
    color: "#ecfccb",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成白色碳酸钡沉淀",
  },
  "CuSO4+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄",
    color: "#38bdf8",
    ph: 10,
    tempDelta: 2,
    effect: "precipitate",
    precipitateColor: "#0ea5e9",
    description: "生成蓝色氢氧化铜沉淀",
  },
  "CuSO4+BaCl2": {
    type: REACTION_TYPES.Precipitation,
    equation: "CuSO₄ + BaCl₂ → BaSO₄↓ + CuCl₂",
    color: "#38bdf8",
    ph: 5,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "硫酸铜与氯化钡反应",
  },
  "FeCl3+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl",
    color: "#fca5a5",
    ph: 11,
    tempDelta: 3,
    effect: "precipitate",
    precipitateColor: "#b45309",
    description: "生成红褐色氢氧化铁沉淀",
  },
  "FeSO4+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "FeSO₄ + 2NaOH → Fe(OH)₂↓ + Na₂SO₄",
    color: "#86efac",
    ph: 10,
    tempDelta: 2,
    effect: "precipitate",
    precipitateColor: "#d1fae5",
    description: "生成白色氢氧化亚铁沉淀，迅速变灰绿色最终氧化为红褐色",
    colorSequence: [
      { color: "#f0fdf4", duration: 0, label: "白色絮状沉淀" },
      { color: "#bbf7d0", duration: 500, label: "开始变灰绿" },
      { color: "#86efac", duration: 1000, label: "灰绿色" },
      { color: "#fca5a5", duration: 2000, label: "氧化为红褐色" },
      { color: "#fecaca", duration: 3000, label: "最终红褐色 Fe(OH)₃" },
    ],
  },
  "FeCl3+NH3H2O": {
    type: REACTION_TYPES.Precipitation,
    equation: "FeCl₃ + 3NH₃·H₂O → Fe(OH)₃↓ + 3NH₄Cl",
    color: "#fca5a5",
    ph: 9,
    tempDelta: 1,
    effect: "precipitate",
    precipitateColor: "#b45309",
    description: "氯化铁与氨水反应生成红褐色沉淀",
  },
  "AlCl3+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "AlCl₃ + 3NaOH → Al(OH)₃↓ + 3NaCl（适量NaOH）",
    color: "#dbeafe",
    ph: 9,
    tempDelta: 1,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "生成白色氢氧化铝沉淀（适量碱）",
  },
  "AlCl3+NH3H2O": {
    type: REACTION_TYPES.Precipitation,
    equation: "AlCl₃ + 3NH₃·H₂O → Al(OH)₃↓ + 3NH₄Cl",
    color: "#dbeafe",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "铝盐与氨水反应生成氢氧化铝沉淀",
  },
  "Al2(SO4)3+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "Al₂(SO₄)₃ + 6NaOH → 2Al(OH)₃↓ + 3Na₂SO₄（适量NaOH）",
    color: "#dbeafe",
    ph: 9,
    tempDelta: 1,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "硫酸铝与适量氢氧化钠反应",
  },
  "MgCl2+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "MgCl₂ + 2NaOH → Mg(OH)₂↓ + 2NaCl",
    color: "#e0e7ff",
    ph: 10,
    tempDelta: 1,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "生成白色氢氧化镁沉淀",
  },
  "ZnSO4+NaOH": {
    type: REACTION_TYPES.Precipitation,
    equation: "ZnSO₄ + 2NaOH → Zn(OH)₂↓ + Na₂SO₄（适量NaOH）",
    color: "#dbeafe",
    ph: 9,
    tempDelta: 1,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "生成白色氢氧化锌沉淀（两性，溶于过量碱）",
  },
  "Pb(NO3)2+KI": {
    type: REACTION_TYPES.Precipitation,
    equation: "Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃",
    color: "#fef9c3",
    ph: 5,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#fbbf24",
    description: "生成黄色碘化铅沉淀（黄金雨实验）",
  },
  "Na2SiO3+HCl": {
    type: REACTION_TYPES.Precipitation,
    equation: "Na₂SiO₃ + 2HCl → 2NaCl + H₂SiO₃↓",
    color: "#d1fae5",
    ph: 2,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "生成白色硅酸沉淀（凝胶状）",
  },
};

// ==================== 络合反应 ====================
const complexationRecipes = {
  "FeCl3+KSCN": {
    type: REACTION_TYPES.Complexation,
    equation: "FeCl₃ + 3KSCN → Fe(SCN)₃ + 3KCl",
    color: "#ef4444",
    ph: 5,
    tempDelta: 0,
    effect: "colorChange",
    precipitateColor: "#dc2626",
    description: "铁离子与硫氰酸根络合，溶液变为血红色",
  },
};

// ==================== 置换反应 ====================
const displacementRecipes = {
  "HCl+Mg": {
    type: REACTION_TYPES.Displacement,
    equation: "2HCl + Mg → MgCl₂ + H₂↑",
    color: "#d8b4fe",
    ph: 3,
    tempDelta: 25,
    effect: "gas",
    description: "镁与盐酸反应剧烈，产生氢气",
  },
  "HCl+Zn": {
    type: REACTION_TYPES.Displacement,
    equation: "2HCl + Zn → ZnCl₂ + H₂↑",
    color: "#c4b5fd",
    ph: 3,
    tempDelta: 15,
    effect: "gas",
    description: "锌与盐酸反应产生氢气",
  },
  "HCl+Fe": {
    type: REACTION_TYPES.Displacement,
    equation: "2HCl + Fe → FeCl₂ + H₂↑",
    color: "#86efac",
    ph: 3,
    tempDelta: 12,
    effect: "gas",
    description: "铁与盐酸反应，溶液变为浅绿色",
  },
  "HCl+Al": {
    type: REACTION_TYPES.Displacement,
    equation: "6HCl + 2Al → 2AlCl₃ + 3H₂↑",
    color: "#93c5fd",
    ph: 3,
    tempDelta: 30,
    effect: "gas",
    description: "铝与盐酸反应",
  },
  "H2SO4+Mg": {
    type: REACTION_TYPES.Displacement,
    equation: "H₂SO₄ + Mg → MgSO₄ + H₂↑",
    color: "#d8b4fe",
    ph: 2,
    tempDelta: 28,
    effect: "gas",
    description: "镁与稀硫酸反应",
  },
  "H2SO4+Zn": {
    type: REACTION_TYPES.Displacement,
    equation: "H₂SO₄ + Zn → ZnSO₄ + H₂↑",
    color: "#c4b5fd",
    ph: 2,
    tempDelta: 20,
    effect: "gas",
    description: "锌与稀硫酸反应",
  },
  "H2SO4+Fe": {
    type: REACTION_TYPES.Displacement,
    equation: "H₂SO₄ + Fe → FeSO₄ + H₂↑",
    color: "#86efac",
    ph: 3,
    tempDelta: 12,
    effect: "gas",
    description: "铁与稀硫酸反应",
  },
  "H2SO4+Al": {
    type: REACTION_TYPES.Displacement,
    equation: "3H₂SO₄ + 2Al → Al₂(SO₄)₃ + 3H₂↑",
    color: "#93c5fd",
    ph: 2,
    tempDelta: 35,
    effect: "gas",
    description: "铝与稀硫酸反应",
  },
  "CuSO4+Fe": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + CuSO₄ → FeSO₄ + Cu",
    color: "#4ade80",
    ph: 5,
    tempDelta: 3,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "铁置换出铜，铁表面出现红色固体",
  },
  "CuSO4+Zn": {
    type: REACTION_TYPES.Displacement,
    equation: "Zn + CuSO₄ → ZnSO₄ + Cu",
    color: "#d1d5db",
    ph: 5,
    tempDelta: 5,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "锌置换出铜",
  },
  "CuSO4+Mg": {
    type: REACTION_TYPES.Displacement,
    equation: "Mg + CuSO₄ → MgSO₄ + Cu",
    color: "#d1d5db",
    ph: 5,
    tempDelta: 8,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "镁置换出铜",
  },
  "AgNO3+Cu": {
    type: REACTION_TYPES.Displacement,
    equation: "Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag",
    color: "#60a5fa",
    ph: 5,
    tempDelta: 8,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "铜置换出银，铜表面出现银白色固体",
  },
  "AgNO3+Fe": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + 2AgNO₃ → Fe(NO₃)₂ + 2Ag",
    color: "#86efac",
    ph: 5,
    tempDelta: 6,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "铁置换出银",
  },
  "AgNO3+Zn": {
    type: REACTION_TYPES.Displacement,
    equation: "Zn + 2AgNO₃ → Zn(NO₃)₂ + 2Ag",
    color: "#cbd5e1",
    ph: 5,
    tempDelta: 5,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "锌置换出银",
  },
  "NaOH+Al": {
    type: REACTION_TYPES.Displacement,
    equation: "2NaOH + 2Al + 2H₂O → 2NaAlO₂ + 3H₂↑",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 20,
    effect: "gas",
    description: "铝与氢氧化钠溶液反应（铝的两性）",
  },
  "FeCl3+Cu": {
    type: REACTION_TYPES.Redox,
    equation: "2FeCl₃ + Cu → 2FeCl₂ + CuCl₂",
    color: "#86efac",
    ph: 4,
    tempDelta: 5,
    effect: "heat",
    description: "铜与氯化铁反应（湿法刻蚀铜）",
  },
};

// ==================== 氧化物反应 ====================
const oxideRecipes = {
  "CuO+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CuO + 2HCl → CuCl₂ + H₂O",
    color: "#22d3ee",
    ph: 3,
    tempDelta: 10,
    effect: "heat",
    description: "黑色氧化铜溶解，溶液变为蓝绿色",
  },
  "CuO+H2SO4": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CuO + H₂SO₄ → CuSO₄ + H₂O",
    color: "#38bdf8",
    ph: 3,
    tempDelta: 12,
    effect: "heat",
    description: "黑色氧化铜溶解，溶液变为蓝色",
  },
  "CuO+HNO3": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CuO + 2HNO₃ → Cu(NO₃)₂ + H₂O",
    color: "#22d3ee",
    ph: 2,
    tempDelta: 11,
    effect: "heat",
    description: "氧化铜溶于硝酸",
  },
  "Fe2O3+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O",
    color: "#fbbf24",
    ph: 2,
    tempDelta: 8,
    effect: "heat",
    description: "铁锈溶解，溶液变为黄色",
  },
  "Fe2O3+H2SO4": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Fe₂O₃ + 3H₂SO₄ → Fe₂(SO₄)₃ + 3H₂O",
    color: "#fca5a5",
    ph: 2,
    tempDelta: 10,
    effect: "heat",
    description: "氧化铁与硫酸反应",
  },
  "Fe2O3+HNO3": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Fe₂O₃ + 6HNO₃ → 2Fe(NO₃)₃ + 3H₂O",
    color: "#fbbf24",
    ph: 1,
    tempDelta: 9,
    effect: "heat",
    description: "氧化铁溶于硝酸",
  },
  "Al2O3+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Al₂O₃ + 6HCl → 2AlCl₃ + 3H₂O",
    color: "#dbeafe",
    ph: 3,
    tempDelta: 8,
    effect: "heat",
    description: "氧化铝溶于盐酸（两性氧化物）",
  },
  "Al2O3+NaOH": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Al₂O₃ + 2NaOH → 2NaAlO₂ + H₂O",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 5,
    effect: "heat",
    description: "氧化铝溶于氢氧化钠（两性氧化物）",
  },
  "Al2O3+H2SO4": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Al₂O₃ + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂O",
    color: "#dbeafe",
    ph: 2,
    tempDelta: 10,
    effect: "heat",
    description: "氧化铝溶于硫酸",
  },
  "MgO+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "MgO + 2HCl → MgCl₂ + H₂O",
    color: "#e0e7ff",
    ph: 4,
    tempDelta: 8,
    effect: "heat",
    description: "氧化镁溶于盐酸",
  },
  "MgO+H2SO4": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "MgO + H₂SO₄ → MgSO₄ + H₂O",
    color: "#e0e7ff",
    ph: 4,
    tempDelta: 10,
    effect: "heat",
    description: "氧化镁溶于硫酸",
  },
  "ZnO+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "ZnO + 2HCl → ZnCl₂ + H₂O",
    color: "#dbeafe",
    ph: 4,
    tempDelta: 8,
    effect: "heat",
    description: "氧化锌溶于盐酸（两性氧化物）",
  },
  "ZnO+NaOH": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "ZnO + 2NaOH → Na₂ZnO₂ + H₂O",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 5,
    effect: "heat",
    description: "氧化锌溶于氢氧化钠（两性氧化物）",
  },
  "CaO+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CaO + H₂O → Ca(OH)₂",
    color: "#fef9c3",
    ph: 12,
    tempDelta: 65,
    effect: "heat",
    description: "生石灰遇水剧烈放热",
  },
  "CaO+HCl": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CaO + 2HCl → CaCl₂ + H₂O",
    color: "#fef9c3",
    ph: 4,
    tempDelta: 15,
    effect: "heat",
    description: "氧化钙与盐酸反应",
  },
  "Na2O+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Na₂O + H₂O → 2NaOH",
    color: "#e2e8f0",
    ph: 14,
    tempDelta: 55,
    effect: "heat",
    description: "氧化钠与水反应生成氢氧化钠",
  },
  "Na2O2+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "2Na₂O₂ + 2H₂O → 4NaOH + O₂↑",
    color: "#fef08a",
    ph: 14,
    tempDelta: 45,
    effect: "gas",
    description: "过氧化钠与水反应，产生氧气",
  },
  "Na2O2+CO2": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "2Na₂O₂ + 2CO₂ → 2Na₂CO₃ + O₂",
    color: "#fef08a",
    ph: 11,
    tempDelta: 20,
    effect: "gas",
    description: "过氧化钠与二氧化碳反应（供氧剂）",
  },
  "CO2+NaOH": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CO₂ + 2NaOH → Na₂CO₃ + H₂O",
    color: "#d1d5db",
    ph: 11,
    tempDelta: 5,
    effect: "heat",
    description: "二氧化碳与氢氧化钠反应",
  },
  "CO2+Ca(OH)2": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O",
    color: "#f5f5f4",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "检验二氧化碳：石灰水变浑浊",
  },
  "CO2+NH3H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CO₂ + 2NH₃·H₂O → (NH₄)₂CO₃ + H₂O",
    color: "#67e8f9",
    ph: 9,
    tempDelta: 3,
    effect: "heat",
    description: "二氧化碳与氨水反应",
  },
  "SO2+NaOH": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SO₂ + 2NaOH → Na₂SO₃ + H₂O",
    color: "#d1d5db",
    ph: 10,
    tempDelta: 8,
    effect: "heat",
    description: "二氧化硫与氢氧化钠反应",
  },
  "SO2+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SO₂ + H₂O ⇌ H₂SO₃",
    color: "#d1d5db",
    ph: 4,
    tempDelta: -3,
    effect: "heat",
    description: "二氧化硫溶于水生成亚硫酸",
  },
  "SO3+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SO₃ + H₂O → H₂SO₄",
    color: "#f97316",
    ph: 1,
    tempDelta: 40,
    effect: "heat",
    description: "三氧化硫溶于水生成硫酸",
  },
  "NO2+H2O": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "3NO₂ + H₂O → 2HNO₃ + NO",
    color: "#92400e",
    ph: 1,
    tempDelta: 5,
    effect: "gas",
    description: "二氧化氮溶于水生成硝酸和一氧化氮",
  },
  "SiO2+NaOH": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SiO₂ + 2NaOH → Na₂SiO₃ + H₂O",
    color: "#f3f4f6",
    ph: 12,
    tempDelta: 3,
    effect: "heat",
    description: "二氧化硅与氢氧化钠反应（玻璃瓶不能盛放碱液）",
  },
  "SiO2+HF": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SiO₂ + 4HF → SiF₄↑ + 2H₂O",
    color: "#f3f4f6",
    ph: 2,
    tempDelta: 5,
    effect: "gas",
    description: "二氧化硅与氢氟酸反应（雕刻玻璃）",
  },
};

// ==================== 氧化还原反应 ====================
const redoxRecipes = {
  "C+CuO": {
    type: REACTION_TYPES.Redox,
    equation: "C + 2CuO →(高温) 2Cu + CO₂↑",
    color: "#f59e0b",
    ph: 7,
    tempDelta: 85,
    effect: "smoke",
    description: "碳还原氧化铜",
  },
  "CO+CuO": {
    type: REACTION_TYPES.Redox,
    equation: "CO + CuO →(加热) Cu + CO₂",
    color: "#f59e0b",
    ph: 7,
    tempDelta: 40,
    effect: "heat",
    description: "一氧化碳还原氧化铜",
  },
  "H2+CuO": {
    type: REACTION_TYPES.Redox,
    equation: "H₂ + CuO →(加热) Cu + H₂O",
    color: "#60a5fa",
    ph: 7,
    tempDelta: 35,
    effect: "heat",
    description: "氢气还原氧化铜",
  },
  "Fe2O3+CO": {
    type: REACTION_TYPES.Redox,
    equation: "Fe₂O₃ + 3CO →(高温) 2Fe + 3CO₂",
    color: "#b91c1c",
    ph: 7,
    tempDelta: 75,
    effect: "heat",
    description: "高炉炼铁",
  },
  "Fe2O3+C": {
    type: REACTION_TYPES.Redox,
    equation: "2Fe₂O₃ + 3C →(高温) 4Fe + 3CO₂↑",
    color: "#b91c1c",
    ph: 7,
    tempDelta: 90,
    effect: "smoke",
    description: "碳还原氧化铁",
  },
  "Fe2O3+Al": {
    type: REACTION_TYPES.Redox,
    equation: "Fe₂O₃ + 2Al →(点燃) 2Fe + Al₂O₃",
    color: "#ef4444",
    ph: 7,
    tempDelta: 100,
    effect: "smoke",
    description: "铝热反应（焊接铁轨）",
  },
  "CuO+Al": {
    type: REACTION_TYPES.Redox,
    equation: "3CuO + 2Al →(点燃) 3Cu + Al₂O₃",
    color: "#f59e0b",
    ph: 7,
    tempDelta: 95,
    effect: "smoke",
    description: "铝热反应还原氧化铜",
  },
  "Cl2+NaOH": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + 2NaOH → NaCl + NaClO + H₂O",
    color: "#4ade80",
    ph: 12,
    tempDelta: 10,
    effect: "heat",
    description: "氯气与氢氧化钠反应（制备漂白液）",
  },
  "Cl2+Ca(OH)2": {
    type: REACTION_TYPES.Redox,
    equation: "2Cl₂ + 2Ca(OH)₂ → CaCl₂ + Ca(ClO)₂ + 2H₂O",
    color: "#4ade80",
    ph: 12,
    tempDelta: 12,
    effect: "heat",
    description: "氯气与氢氧化钙反应（制备漂白粉）",
  },
  "Cl2+Fe": {
    type: REACTION_TYPES.Redox,
    equation: "2Fe + 3Cl₂ →(点燃) 2FeCl₃",
    color: "#fca5a5",
    ph: 7,
    tempDelta: 60,
    effect: "smoke",
    description: "铁在氯气中燃烧，产生棕褐色烟",
  },
  "Cl2+Cu": {
    type: REACTION_TYPES.Redox,
    equation: "Cu + Cl₂ →(点燃) CuCl₂",
    color: "#38bdf8",
    ph: 7,
    tempDelta: 50,
    effect: "smoke",
    description: "铜在氯气中燃烧，产生棕黄色烟",
  },
  "Cl2+H2": {
    type: REACTION_TYPES.Redox,
    equation: "H₂ + Cl₂ →(光照) 2HCl",
    color: "#4ade80",
    ph: 1,
    tempDelta: 55,
    effect: "smoke",
    description: "氢气与氯气光照爆炸",
  },
  "Cl2+Na": {
    type: REACTION_TYPES.Redox,
    equation: "2Na + Cl₂ →(点燃) 2NaCl",
    color: "#fef9c3",
    ph: 7,
    tempDelta: 70,
    effect: "smoke",
    description: "钠在氯气中燃烧",
  },
  "FeCl3+Cu": {
    type: REACTION_TYPES.Redox,
    equation: "2FeCl₃ + Cu → 2FeCl₂ + CuCl₂",
    color: "#86efac",
    ph: 4,
    tempDelta: 5,
    effect: "heat",
    description: "铜与氯化铁反应（湿法刻蚀铜）",
  },
  "KMnO4+HCl": {
    type: REACTION_TYPES.Redox,
    equation: "2KMnO₄ + 16HCl → 2KCl + 2MnCl₂ + 5Cl₂↑ + 8H₂O",
    color: "#c084fc",
    ph: 1,
    tempDelta: 15,
    effect: "gas",
    description: "高锰酸钾与浓盐酸反应产生氯气",
  },
  "MnO2+HCl": {
    type: REACTION_TYPES.Redox,
    equation: "MnO₂ + 4HCl(浓) →(加热) MnCl₂ + Cl₂↑ + 2H₂O",
    color: "#1e293b",
    ph: 1,
    tempDelta: 20,
    effect: "gas",
    description: "二氧化锰与浓盐酸反应制氯气",
  },
};

// ==================== 化合反应 ====================
const combinationRecipes = {
  "Na+Cl2": {
    type: REACTION_TYPES.Combination,
    equation: "2Na + Cl₂ →(点燃) 2NaCl",
    color: "#fef9c3",
    ph: 7,
    tempDelta: 70,
    effect: "smoke",
    description: "钠在氯气中燃烧",
  },
  "S+Fe": {
    type: REACTION_TYPES.Combination,
    equation: "Fe + S →(加热) FeS",
    color: "#94a3b8",
    ph: 7,
    tempDelta: 45,
    effect: "heat",
    description: "铁粉与硫粉混合加热",
  },
  "S+Cu": {
    type: REACTION_TYPES.Combination,
    equation: "2Cu + S →(加热) Cu₂S",
    color: "#f59e0b",
    ph: 7,
    tempDelta: 30,
    effect: "heat",
    description: "铜与硫反应生成硫化亚铜",
  },
  "C+O2": {
    type: REACTION_TYPES.Combination,
    equation: "C + O₂ →(点燃) CO₂",
    color: "#9ca3af",
    ph: 7,
    tempDelta: 80,
    effect: "heat",
    description: "碳在氧气中充分燃烧",
  },
  "S+O2": {
    type: REACTION_TYPES.Combination,
    equation: "S + O₂ →(点燃) SO₂",
    color: "#d1d5db",
    ph: 7,
    tempDelta: 60,
    effect: "smoke",
    description: "硫在氧气中燃烧，产生蓝紫色火焰",
  },
  "P+O2": {
    type: REACTION_TYPES.Combination,
    equation: "4P + 5O₂ →(点燃) 2P₂O₅",
    color: "#f5f5f4",
    ph: 7,
    tempDelta: 70,
    effect: "smoke",
    description: "磷在氧气中燃烧，产生大量白烟",
  },
  "Mg+O2": {
    type: REACTION_TYPES.Combination,
    equation: "2Mg + O₂ →(点燃) 2MgO",
    color: "#f5f5f4",
    ph: 7,
    tempDelta: 85,
    effect: "smoke",
    description: "镁在氧气中燃烧，发出耀眼白光",
  },
  "Fe+O2": {
    type: REACTION_TYPES.Combination,
    equation: "3Fe + 2O₂ →(点燃) Fe₃O₄",
    color: "#1e293b",
    ph: 7,
    tempDelta: 75,
    effect: "smoke",
    description: "铁在氧气中燃烧，火星四射",
  },
  "Cu+O2": {
    type: REACTION_TYPES.Combination,
    equation: "2Cu + O₂ →(加热) 2CuO",
    color: "#1e293b",
    ph: 7,
    tempDelta: 40,
    effect: "heat",
    description: "铜在空气中加热变黑",
  },
  "N2+O2": {
    type: REACTION_TYPES.Combination,
    equation: "N₂ + O₂ →(放电) 2NO",
    color: "#9ca3af",
    ph: 7,
    tempDelta: 100,
    effect: "heat",
    description: "氮气与氧气在放电条件下反应",
  },
  "H2+O2": {
    type: REACTION_TYPES.Combination,
    equation: "2H₂ + O₂ →(点燃) 2H₂O",
    color: "#60a5fa",
    ph: 7,
    tempDelta: 90,
    effect: "heat",
    description: "氢气在氧气中燃烧",
  },
  "CO+O2": {
    type: REACTION_TYPES.Combination,
    equation: "2CO + O₂ →(点燃) 2CO₂",
    color: "#9ca3af",
    ph: 7,
    tempDelta: 85,
    effect: "heat",
    description: "一氧化碳在氧气中燃烧（蓝色火焰）",
  },
  "CH4+O2": {
    type: REACTION_TYPES.Combination,
    equation: "CH₄ + 2O₂ →(点燃) CO₂ + 2H₂O",
    color: "#60a5fa",
    ph: 7,
    tempDelta: 80,
    effect: "heat",
    description: "甲烷在氧气中燃烧（天然气燃烧）",
  },
};

// ==================== 分解反应 ====================
const decompositionRecipes = {
  "H2O2": {
    type: REACTION_TYPES.Decomposition,
    equation: "2H₂O₂ →(MnO₂) 2H₂O + O₂↑",
    color: "#bfdbfe",
    ph: 7,
    tempDelta: -5,
    effect: "gas",
    description: "过氧化氢分解产生氧气",
  },
  "H2O": {
    type: REACTION_TYPES.Decomposition,
    equation: "2H₂O →(通电) 2H₂↑ + O₂↑",
    color: "#60a5fa",
    ph: 7,
    tempDelta: -10,
    effect: "gas",
    description: "电解水",
  },
  "CaCO3+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "CaCO₃ →(高温) CaO + CO₂↑",
    color: "#d9f99d",
    ph: 7,
    tempDelta: 80,
    effect: "gas",
    description: "石灰石高温分解",
  },
  "NaHCO3+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "2NaHCO₃ →(加热) Na₂CO₃ + H₂O + CO₂↑",
    color: "#fef08a",
    ph: 9,
    tempDelta: 30,
    effect: "gas",
    description: "碳酸氢钠受热分解",
  },
  "NH4HCO3+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "NH₄HCO₃ →(加热) NH₃↑ + H₂O + CO₂↑",
    color: "#67e8f9",
    ph: 7,
    tempDelta: 25,
    effect: "gas",
    description: "碳酸氢铵受热分解",
  },
  "KClO3+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "2KClO₃ →(MnO₂/加热) 2KCl + 3O₂↑",
    color: "#f5f5f4",
    ph: 7,
    tempDelta: 20,
    effect: "gas",
    description: "氯酸钾分解制氧气",
  },
  "KMnO4+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "2KMnO₄ →(加热) K₂MnO₄ + MnO₂ + O₂↑",
    color: "#c084fc",
    ph: 7,
    tempDelta: 15,
    effect: "gas",
    description: "高锰酸钾受热分解",
  },
  "Cu(OH)2+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "Cu(OH)₂ →(加热) CuO + H₂O",
    color: "#1e293b",
    ph: 7,
    tempDelta: 10,
    effect: "heat",
    description: "氢氧化铜受热分解",
  },
  "Fe(OH)3+heat": {
    type: REACTION_TYPES.Decomposition,
    equation: "2Fe(OH)₃ →(加热) Fe₂O₃ + 3H₂O",
    color: "#b91c1c",
    ph: 7,
    tempDelta: 12,
    effect: "heat",
    description: "氢氧化铁受热分解",
  },
};

// ==================== 钠的特殊反应 ====================
const sodiumRecipes = {
  "Na+H2O": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "2Na + 2H₂O → 2NaOH + H₂↑",
    color: "#e2e8f0",
    ph: 13,
    tempDelta: 80,
    effect: "smoke",
    description: "钠与水剧烈反应",
  },
  "Na+HCl": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "2Na + 2HCl → 2NaCl + H₂↑",
    color: "#fef08a",
    ph: 7,
    tempDelta: 85,
    effect: "smoke",
    description: "钠与盐酸剧烈反应",
  },
};

// ==================== 三元反应 ====================
const ternaryRecipes = {
  "HCl+NaOH+酚酞": {
    type: REACTION_TYPES.Neutralization,
    equation: "HCl + NaOH → NaCl + H₂O（酚酞指示剂）",
    color: "#f472b6",
    ph: 7,
    tempDelta: 15,
    effect: "colorChange",
    description: "酸碱中和滴定，酚酞由红色变为无色",
    reactants: ["HCl", "NaOH", "酚酞"],
  },
  "Fe+CuSO4+AgNO3": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + CuSO₄ → FeSO₄ + Cu; Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag",
    color: "#e5e7eb",
    ph: 5,
    tempDelta: 8,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "铁先置换铜，铜再置换银",
    reactants: ["Fe", "CuSO4", "AgNO3"],
  },
};

// ==================== 合并所有反应 ====================
export const reactionRecipes = {
  ...acidBaseRecipes,
  ...gasProductionRecipes,
  ...precipitationRecipes,
  ...complexationRecipes,
  ...displacementRecipes,
  ...oxideRecipes,
  ...redoxRecipes,
  ...combinationRecipes,
  ...decompositionRecipes,
  ...sodiumRecipes,
  ...ternaryRecipes,
  ...indicatorRecipes,
  ...metalWaterRecipes,
  ...amphotericRecipes,
  ...ionTestRecipes,
  ...nonmetalOxideRecipes,
  ...ironCopperRecipes,
  ...industrialRecipes,
  ...organicRecipes,
  ...moreRedoxRecipes,
  ...morePrecipitateRecipes,
};

// ==================== 反应索引（用于快速匹配） ====================
const reactionIndex = new Map();

Object.entries(reactionRecipes).forEach(([key, recipe]) => {
  let reactants;
  if (recipe.reactants) {
    reactants = recipe.reactants;
  } else {
    reactants = key.split("+");
  }
  const sortedKey = [...reactants].sort().join("+");
  reactionIndex.set(sortedKey, { key, recipe, reactants });
});

// ==================== 匹配函数 ====================
function getSortedKey(reactants) {
  return [...reactants].sort().join("+");
}

export function findReaction(existing, incoming) {
  // 确保 existing 是数组
  const existingArray = Array.isArray(existing) ? existing : [existing];
  const allReactants = [...existingArray, incoming];
  const sortedKey = getSortedKey(allReactants);

  // 精确匹配：所有反应物完全匹配
  const exactMatch = reactionIndex.get(sortedKey);
  if (exactMatch) {
    return { key: exactMatch.key, ...exactMatch.recipe };
  }

  // 子集匹配：检查是否有反应是当前试剂的子集
  for (const [indexKey, { key, recipe, reactants }] of reactionIndex) {
    const isSubset = reactants.every((r) => allReactants.includes(r));
    if (isSubset && reactants.length === allReactants.length) {
      return { key, ...recipe };
    }
  }

  // 向前兼容：尝试旧的二元匹配方式
  for (const reagent of existingArray) {
    const key1 = `${reagent}+${incoming}`;
    const key2 = `${incoming}+${reagent}`;
    if (reactionRecipes[key1]) return { key: key1, ...reactionRecipes[key1] };
    if (reactionRecipes[key2]) return { key: key2, ...reactionRecipes[key2] };
  }

  // 单物质反应（分解反应等）
  if (reactionRecipes[incoming]) {
    return { key: incoming, ...reactionRecipes[incoming] };
  }

  return null;
}

export function getReactionKey(a, b) {
  const key1 = `${a}+${b}`;
  const key2 = `${b}+${a}`;
  if (reactionRecipes[key1]) return key1;
  if (reactionRecipes[key2]) return key2;
  if (reactionRecipes[a]) return a;
  if (reactionRecipes[b]) return b;
  return null;
}
