// 补充反应 - 高中化学全面覆盖
// 包含：酸碱指示剂、金属与水、离子检验、有机化学、工业流程等

import { REACTION_TYPES } from "../../constants/labConfig";

// ==================== 酸碱指示剂反应 ====================
export const indicatorRecipes = {
  "HCl+酚酞": {
    type: REACTION_TYPES.Neutralization,
    equation: "酚酞在酸性溶液中呈无色",
    color: "#f5f5f4",
    ph: 1,
    tempDelta: 0,
    effect: "colorChange",
    description: "酚酞指示剂在酸性条件下为无色",
  },
  "NaOH+酚酞": {
    type: REACTION_TYPES.Neutralization,
    equation: "酚酞在碱性溶液中呈红色",
    color: "#ef4444",
    ph: 14,
    tempDelta: 0,
    effect: "colorChange",
    description: "酚酞指示剂在碱性条件下变红",
  },
  "HCl+石蕊": {
    type: REACTION_TYPES.Neutralization,
    equation: "石蕊在酸性溶液中呈红色",
    color: "#ef4444",
    ph: 1,
    tempDelta: 0,
    effect: "colorChange",
    description: "石蕊指示剂遇酸变红",
  },
  "NaOH+石蕊": {
    type: REACTION_TYPES.Neutralization,
    equation: "石蕊在碱性溶液中呈蓝色",
    color: "#3b82f6",
    ph: 14,
    tempDelta: 0,
    effect: "colorChange",
    description: "石蕊指示剂遇碱变蓝",
  },
  "HCl+甲基橙": {
    type: REACTION_TYPES.Neutralization,
    equation: "甲基橙在酸性溶液中呈红色",
    color: "#ef4444",
    ph: 1,
    tempDelta: 0,
    effect: "colorChange",
    description: "甲基橙指示剂在酸性条件下为红色",
  },
  "NaOH+甲基橙": {
    type: REACTION_TYPES.Neutralization,
    equation: "甲基橙在碱性溶液中呈黄色",
    color: "#eab308",
    ph: 14,
    tempDelta: 0,
    effect: "colorChange",
    description: "甲基橙指示剂在碱性条件下为黄色",
  },
};

// ==================== 金属与水/酸反应 ====================
export const metalWaterRecipes = {
  "K+H2O": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "2K + 2H₂O → 2KOH + H₂↑",
    color: "#f472b6",
    ph: 14,
    tempDelta: 90,
    effect: "smoke",
    description: "钾与水剧烈反应，可能燃烧甚至爆炸",
  },
  "Mg+H2O": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "Mg + 2H₂O →(加热) Mg(OH)₂ + H₂↑",
    color: "#f1f5f9",
    ph: 10,
    tempDelta: 30,
    effect: "gas",
    description: "镁与热水反应产生氢气",
  },
  "Fe+H2O": {
    type: REACTION_TYPES.Redox,
    equation: "3Fe + 4H₂O →(高温) Fe₃O₄ + 4H₂↑",
    color: "#1e293b",
    ph: 7,
    tempDelta: 50,
    effect: "gas",
    description: "铁与水蒸气在高温下反应",
  },
  "HCl+K": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "2K + 2HCl → 2KCl + H₂↑",
    color: "#fef08a",
    ph: 7,
    tempDelta: 90,
    effect: "smoke",
    description: "钾与盐酸剧烈反应（比钠更剧烈）",
  },
  "H2SO4+K": {
    type: REACTION_TYPES["Single Displacement"],
    equation: "2K + H₂SO₄ → K₂SO₄ + H₂↑",
    color: "#fef08a",
    ph: 7,
    tempDelta: 88,
    effect: "smoke",
    description: "钾与稀硫酸反应",
  },
};

// ==================== 两性氢氧化物反应 ====================
export const amphotericRecipes = {
  "Al(OH)3+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Al(OH)₃ + 3HCl → AlCl₃ + 3H₂O",
    color: "#dbeafe",
    ph: 4,
    tempDelta: 8,
    effect: "heat",
    description: "氢氧化铝溶于盐酸（两性氢氧化物与酸反应）",
  },
  "Al(OH)3+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "Al(OH)₃ + NaOH → NaAlO₂ + 2H₂O",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 5,
    effect: "heat",
    description: "氢氧化铝溶于氢氧化钠（两性氢氧化物与碱反应）",
  },
  "Zn(OH)2+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Zn(OH)₂ + 2HCl → ZnCl₂ + 2H₂O",
    color: "#dbeafe",
    ph: 4,
    tempDelta: 8,
    effect: "heat",
    description: "氢氧化锌溶于盐酸",
  },
  "Zn(OH)2+NaOH": {
    type: REACTION_TYPES.Neutralization,
    equation: "Zn(OH)₂ + 2NaOH → Na₂ZnO₂ + 2H₂O",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 5,
    effect: "heat",
    description: "氢氧化锌溶于氢氧化钠（两性）",
  },
  "Cu(OH)2+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Cu(OH)₂ + 2HCl → CuCl₂ + 2H₂O",
    color: "#22d3ee",
    ph: 4,
    tempDelta: 8,
    effect: "heat",
    description: "蓝色氢氧化铜溶于盐酸",
  },
  "Cu(OH)2+H2SO4": {
    type: REACTION_TYPES.Neutralization,
    equation: "Cu(OH)₂ + H₂SO₄ → CuSO₄ + 2H₂O",
    color: "#38bdf8",
    ph: 4,
    tempDelta: 10,
    effect: "heat",
    description: "蓝色氢氧化铜溶于硫酸",
  },
  "Mg(OH)2+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O",
    color: "#e0e7ff",
    ph: 5,
    tempDelta: 8,
    effect: "heat",
    description: "氢氧化镁溶于盐酸（中和胃酸）",
  },
  "Fe(OH)3+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Fe(OH)₃ + 3HCl → FeCl₃ + 3H₂O",
    color: "#fca5a5",
    ph: 3,
    tempDelta: 6,
    effect: "heat",
    description: "红褐色氢氧化铁溶于盐酸",
  },
  "Fe(OH)2+HCl": {
    type: REACTION_TYPES.Neutralization,
    equation: "Fe(OH)₂ + 2HCl → FeCl₂ + 2H₂O",
    color: "#86efac",
    ph: 4,
    tempDelta: 6,
    effect: "heat",
    description: "白色氢氧化亚铁溶于盐酸",
  },
};

// ==================== 离子检验反应 ====================
export const ionTestRecipes = {
  "Na2CO3+CaCl2": {
    type: REACTION_TYPES.Precipitation,
    equation: "Na₂CO₃ + CaCl₂ → CaCO₃↓ + 2NaCl",
    color: "#fefce8",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "检验碳酸根离子：生成白色沉淀",
  },
  "Na2SO4+BaCl2": {
    type: REACTION_TYPES.Precipitation,
    equation: "Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl",
    color: "#f1f5f9",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "检验硫酸根离子：加BaCl₂生成白色沉淀",
  },
  "NaCl+AgNO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "NaCl + AgNO₃ → AgCl↓ + NaNO₃",
    color: "#e5e7eb",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f8fafc",
    description: "检验氯离子：加AgNO₃生成白色沉淀",
  },
  "KI+AgNO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "KI + AgNO₃ → AgI↓ + KNO₃",
    color: "#fef9c3",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#fbbf24",
    description: "检验碘离子：生成黄色沉淀",
  },
  "Na2SO3+HCl": {
    type: REACTION_TYPES["Gas Production"],
    equation: "Na₂SO₃ + 2HCl → 2NaCl + H₂O + SO₂↑",
    color: "#d1d5db",
    ph: 3,
    tempDelta: -2,
    effect: "gas",
    description: "亚硫酸盐与酸反应产生二氧化硫",
  },
  "Na2S+HCl": {
    type: REACTION_TYPES["Gas Production"],
    equation: "Na₂S + 2HCl → 2NaCl + H₂S↑",
    color: "#fbbf24",
    ph: 3,
    tempDelta: 0,
    effect: "gas",
    description: "硫化钠与酸反应产生臭鸡蛋气味的硫化氢",
  },
  "Na2S+CuSO4": {
    type: REACTION_TYPES.Precipitation,
    equation: "Na₂S + CuSO₄ → CuS↓ + Na₂SO₄",
    color: "#1e293b",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#1e293b",
    description: "生成黑色硫化铜沉淀",
  },
};

// ==================== 非金属氧化物与碱 / 卤素反应 ====================
export const nonmetalOxideRecipes = {
  "CO2+NaOH_过量": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CO₂ + NaOH → NaHCO₃",
    color: "#d1d5db",
    ph: 8,
    tempDelta: 3,
    effect: "heat",
    description: "过量CO₂与NaOH反应生成碳酸氢钠",
  },
  "SO2+NaOH_过量": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SO₂ + NaOH → NaHSO₃",
    color: "#d1d5db",
    ph: 6,
    tempDelta: 5,
    effect: "heat",
    description: "过量SO₂与NaOH反应生成亚硫酸氢钠",
  },
  "CO2+Ba(OH)2": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CO₂ + Ba(OH)₂ → BaCO₃↓ + H₂O",
    color: "#f5f5f4",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "二氧化碳使氢氧化钡溶液变浑浊",
  },
  "SO2+品红": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "SO₂使品红溶液褪色",
    color: "#fef9c3",
    ph: 5,
    tempDelta: 0,
    effect: "colorChange",
    description: "二氧化硫的漂白性：使品红溶液褪色（加热恢复）",
  },
  "Cl2+H2O": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + H₂O ⇌ HCl + HClO",
    color: "#4ade80",
    ph: 4,
    tempDelta: -2,
    effect: "heat",
    description: "氯气溶于水生成盐酸和次氯酸（氯水）",
  },
  "Cl2+KI": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + 2KI → 2KCl + I₂",
    color: "#6366f1",
    ph: 7,
    tempDelta: 5,
    effect: "colorChange",
    description: "氯气置换碘：溶液变为棕褐色",
  },
  "Cl2+Na2S": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + Na₂S → 2NaCl + S↓",
    color: "#fbbf24",
    ph: 7,
    tempDelta: 5,
    effect: "precipitate",
    precipitateColor: "#fbbf24",
    description: "氯气氧化硫化钠，生成淡黄色硫沉淀",
  },
  "Cl2+FeCl2": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + 2FeCl₂ → 2FeCl₃",
    color: "#fca5a5",
    ph: 3,
    tempDelta: 8,
    effect: "heat",
    description: "氯气氧化氯化亚铁为氯化铁",
  },
  "Cl2+H2S": {
    type: REACTION_TYPES.Redox,
    equation: "Cl₂ + H₂S → 2HCl + S↓",
    color: "#fbbf24",
    ph: 1,
    tempDelta: 10,
    effect: "precipitate",
    precipitateColor: "#fbbf24",
    description: "氯气氧化硫化氢，生成淡黄色硫沉淀",
  },
};

// ==================== 金属置换/铜铁反应 ====================
export const ironCopperRecipes = {
  "Fe+HCl": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + 2HCl → FeCl₂ + H₂↑",
    color: "#86efac",
    ph: 3,
    tempDelta: 12,
    effect: "gas",
    description: "铁与盐酸反应，溶液变为浅绿色",
  },
  "Fe+H2SO4": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + H₂SO₄ → FeSO₄ + H₂↑",
    color: "#86efac",
    ph: 3,
    tempDelta: 12,
    effect: "gas",
    description: "铁与稀硫酸反应，溶液变为浅绿色",
  },
  "Fe+CuSO4": {
    type: REACTION_TYPES.Displacement,
    equation: "Fe + CuSO₄ → FeSO₄ + Cu",
    color: "#4ade80",
    ph: 5,
    tempDelta: 3,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "铁置换铜（湿法炼铜）：铁表面出现红色固体",
  },
  "Cu+AgNO3": {
    type: REACTION_TYPES.Displacement,
    equation: "Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag",
    color: "#60a5fa",
    ph: 5,
    tempDelta: 8,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "铜置换银：铜表面出现银白色固体",
  },
  "Zn+CuSO4": {
    type: REACTION_TYPES.Displacement,
    equation: "Zn + CuSO₄ → ZnSO₄ + Cu",
    color: "#d1d5db",
    ph: 5,
    tempDelta: 5,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "锌置换铜：锌表面出现红色固体",
  },
  "Zn+AgNO3": {
    type: REACTION_TYPES.Displacement,
    equation: "Zn + 2AgNO₃ → Zn(NO₃)₂ + 2Ag",
    color: "#cbd5e1",
    ph: 5,
    tempDelta: 5,
    effect: "precipitate",
    precipitateColor: "#e5e7eb",
    description: "锌置换银",
  },
  "Mg+CuSO4": {
    type: REACTION_TYPES.Displacement,
    equation: "Mg + CuSO₄ → MgSO₄ + Cu",
    color: "#d1d5db",
    ph: 5,
    tempDelta: 8,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "镁置换铜",
  },
  "Al+CuSO4": {
    type: REACTION_TYPES.Displacement,
    equation: "2Al + 3CuSO₄ → Al₂(SO₄)₃ + 3Cu",
    color: "#93c5fd",
    ph: 5,
    tempDelta: 10,
    effect: "precipitate",
    precipitateColor: "#f59e0b",
    description: "铝置换铜",
  },
  "Cu+FeCl3": {
    type: REACTION_TYPES.Redox,
    equation: "Cu + 2FeCl₃ → CuCl₂ + 2FeCl₂",
    color: "#86efac",
    ph: 4,
    tempDelta: 5,
    effect: "heat",
    description: "铜与氯化铁反应（湿法刻蚀铜电路板）",
  },
};

// ==================== 工业流程反应 ====================
export const industrialRecipes = {
  "Al2O3+NaOH_工业": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "Al₂O₃ + 2NaOH →(高温) 2NaAlO₂ + H₂O",
    color: "#dbeafe",
    ph: 12,
    tempDelta: 15,
    effect: "heat",
    description: "工业制铝：铝土矿溶于NaOH（碱溶法）",
  },
  "NaAlO2+CO2": {
    type: REACTION_TYPES.Precipitation,
    equation: "NaAlO₂ + CO₂ + 2H₂O → Al(OH)₃↓ + NaHCO₃",
    color: "#dbeafe",
    ph: 8,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f1f5f9",
    description: "通入CO₂沉淀出氢氧化铝（工业制铝步骤）",
  },
  "CaO+SiO2": {
    type: REACTION_TYPES["Oxide Reaction"],
    equation: "CaO + SiO₂ →(高温) CaSiO₃",
    color: "#f1f5f9",
    ph: 7,
    tempDelta: 30,
    effect: "heat",
    description: "高炉炼铁中造渣反应",
  },
};

// ==================== 有机化学基础反应 ====================
export const organicRecipes = {
  "C2H4+溴水": {
    type: REACTION_TYPES.Redox,
    equation: "C₂H₄ + Br₂ → CH₂BrCH₂Br",
    color: "#fef9c3",
    ph: 7,
    tempDelta: 5,
    effect: "colorChange",
    description: "乙烯使溴水褪色（加成反应）",
  },
  "C2H4+酸性KMnO4": {
    type: REACTION_TYPES.Redox,
    equation: "C₂H₄被酸性KMnO₄氧化",
    color: "#fef9c3",
    ph: 3,
    tempDelta: 5,
    effect: "colorChange",
    description: "乙烯使酸性高锰酸钾溶液褪色（氧化反应）",
  },
  "C2H2+溴水": {
    type: REACTION_TYPES.Redox,
    equation: "C₂H₂ + 2Br₂ → CHBr₂CHBr₂",
    color: "#fef9c3",
    ph: 7,
    tempDelta: 5,
    effect: "colorChange",
    description: "乙炔使溴水褪色（加成反应，1:2加成）",
  },
  "C2H2+酸性KMnO4": {
    type: REACTION_TYPES.Redox,
    equation: "C₂H₂被酸性KMnO₄氧化",
    color: "#fef9c3",
    ph: 3,
    tempDelta: 5,
    effect: "colorChange",
    description: "乙炔使酸性高锰酸钾溶液褪色",
  },
  "淀粉+I2": {
    type: REACTION_TYPES.Complexation,
    equation: "淀粉 + I₂ → 蓝色络合物",
    color: "#1d4ed8",
    ph: 7,
    tempDelta: 0,
    effect: "colorChange",
    description: "淀粉遇碘变蓝色（检验淀粉或碘）",
  },
};

// ==================== 更多氧化还原反应 ====================
export const moreRedoxRecipes = {
  "HNO3+Cu": {
    type: REACTION_TYPES.Redox,
    equation: "3Cu + 8HNO₃(稀) → 3Cu(NO₃)₂ + 2NO↑ + 4H₂O",
    color: "#60a5fa",
    ph: 2,
    tempDelta: 15,
    effect: "gas",
    description: "铜与稀硝酸反应（产生无色NO气体）",
  },
  "HNO3+Cu_浓": {
    type: REACTION_TYPES.Redox,
    equation: "Cu + 4HNO₃(浓) → Cu(NO₃)₂ + 2NO₂↑ + 2H₂O",
    color: "#92400e",
    ph: 1,
    tempDelta: 20,
    effect: "gas",
    description: "铜与浓硝酸反应（产生红棕色NO₂气体）",
  },
  "H2SO4+Cu": {
    type: REACTION_TYPES.Redox,
    equation: "Cu + 2H₂SO₄(浓) →(加热) CuSO₄ + SO₂↑ + 2H₂O",
    color: "#38bdf8",
    ph: 1,
    tempDelta: 25,
    effect: "gas",
    description: "铜与浓硫酸加热反应",
  },
  "C+H2SO4_浓": {
    type: REACTION_TYPES.Redox,
    equation: "C + 2H₂SO₄(浓) →(加热) CO₂↑ + 2SO₂↑ + 2H₂O",
    color: "#f97316",
    ph: 1,
    tempDelta: 40,
    effect: "smoke",
    description: "碳与浓硫酸加热反应",
  },
  "Fe+I2": {
    type: REACTION_TYPES.Combination,
    equation: "Fe + I₂ →(加热) FeI₂",
    color: "#94a3b8",
    ph: 7,
    tempDelta: 30,
    effect: "heat",
    description: "铁与碘反应生成碘化亚铁",
  },
};

// ==================== 更多沉淀反应 ====================
export const morePrecipitateRecipes = {
  "CuSO4+Na2S": {
    type: REACTION_TYPES.Precipitation,
    equation: "CuSO₄ + Na₂S → CuS↓ + Na₂SO₄",
    color: "#1e293b",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#1e293b",
    description: "生成黑色硫化铜沉淀",
  },
  "Pb(NO3)2+Na2S": {
    type: REACTION_TYPES.Precipitation,
    equation: "Pb(NO₃)₂ + Na₂S → PbS↓ + 2NaNO₃",
    color: "#1e293b",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#1e293b",
    description: "生成黑色硫化铅沉淀",
  },
  "AgNO3+Na2CO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "2AgNO₃ + Na₂CO₃ → Ag₂CO₃↓ + 2NaNO₃",
    color: "#e5e7eb",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成淡黄色碳酸银沉淀",
  },
  "BaCl2+Na2SO3": {
    type: REACTION_TYPES.Precipitation,
    equation: "BaCl₂ + Na₂SO₃ → BaSO₃↓ + 2NaCl",
    color: "#f1f5f9",
    ph: 7,
    tempDelta: 0,
    effect: "precipitate",
    precipitateColor: "#f5f5f4",
    description: "生成白色亚硫酸钡沉淀（溶于盐酸）",
  },
};
